class AddGrid2ToApproval < ActiveRecord::Migration
  def change
    add_column :approvals, :grid121, :string
    add_column :approvals, :grid122, :string
    add_column :approvals, :grid123, :string
    add_column :approvals, :grid124, :string
    add_column :approvals, :grid125, :string
    add_column :approvals, :grid126, :string
    add_column :approvals, :grid127, :string
    add_column :approvals, :grid131, :string
    add_column :approvals, :grid132, :string
    add_column :approvals, :grid133, :string
    add_column :approvals, :grid134, :string
    add_column :approvals, :grid135, :string
    add_column :approvals, :grid136, :string
    add_column :approvals, :grid137, :string
    add_column :approvals, :grid141, :string
    add_column :approvals, :grid142, :string
    add_column :approvals, :grid143, :string
    add_column :approvals, :grid144, :string
    add_column :approvals, :grid145, :string
    add_column :approvals, :grid146, :string
    add_column :approvals, :grid147, :string
    add_column :approvals, :grid151, :string
    add_column :approvals, :grid152, :string
    add_column :approvals, :grid153, :string
    add_column :approvals, :grid154, :string
    add_column :approvals, :grid155, :string
    add_column :approvals, :grid156, :string
    add_column :approvals, :grid157, :string
    add_column :approvals, :grid161, :string
    add_column :approvals, :grid162, :string
    add_column :approvals, :grid163, :string
    add_column :approvals, :grid164, :string
    add_column :approvals, :grid165, :string
    add_column :approvals, :grid166, :string
    add_column :approvals, :grid167, :string
    add_column :approvals, :grid171, :string
    add_column :approvals, :grid172, :string
    add_column :approvals, :grid173, :string
    add_column :approvals, :grid174, :string
    add_column :approvals, :grid175, :string
    add_column :approvals, :grid176, :string
    add_column :approvals, :grid177, :string
    add_column :approvals, :grid181, :string
    add_column :approvals, :grid182, :string
    add_column :approvals, :grid183, :string
    add_column :approvals, :grid184, :string
    add_column :approvals, :grid185, :string
    add_column :approvals, :grid186, :string
    add_column :approvals, :grid187, :string
    add_column :approvals, :grid191, :string
    add_column :approvals, :grid192, :string
    add_column :approvals, :grid193, :string
    add_column :approvals, :grid194, :string
    add_column :approvals, :grid195, :string
    add_column :approvals, :grid196, :string
    add_column :approvals, :grid197, :string
    add_column :approvals, :grid201, :string
    add_column :approvals, :grid202, :string
    add_column :approvals, :grid203, :string
    add_column :approvals, :grid204, :string
    add_column :approvals, :grid205, :string
    add_column :approvals, :grid206, :string
    add_column :approvals, :grid207, :string
    add_column :approvals, :grid211, :string
    add_column :approvals, :grid212, :string
    add_column :approvals, :grid213, :string
    add_column :approvals, :grid214, :string
    add_column :approvals, :grid215, :string
    add_column :approvals, :grid216, :string
    add_column :approvals, :grid217, :string
    add_column :approvals, :grid221, :string
    add_column :approvals, :grid222, :string
    add_column :approvals, :grid223, :string
    add_column :approvals, :grid224, :string
    add_column :approvals, :grid225, :string
    add_column :approvals, :grid226, :string
    add_column :approvals, :grid227, :string
    add_column :approvals, :grid231, :string
    add_column :approvals, :grid232, :string
    add_column :approvals, :grid233, :string
    add_column :approvals, :grid234, :string
    add_column :approvals, :grid235, :string
    add_column :approvals, :grid236, :string
    add_column :approvals, :grid237, :string
    add_column :approvals, :grid241, :string
    add_column :approvals, :grid242, :string
    add_column :approvals, :grid243, :string
    add_column :approvals, :grid244, :string
    add_column :approvals, :grid245, :string
    add_column :approvals, :grid246, :string
    add_column :approvals, :grid247, :string
    add_column :approvals, :grid251, :string
    add_column :approvals, :grid252, :string
    add_column :approvals, :grid253, :string
    add_column :approvals, :grid254, :string
    add_column :approvals, :grid255, :string
    add_column :approvals, :grid256, :string
    add_column :approvals, :grid257, :string
    add_column :approvals, :grid261, :string
    add_column :approvals, :grid262, :string
    add_column :approvals, :grid263, :string
    add_column :approvals, :grid264, :string
    add_column :approvals, :grid265, :string
    add_column :approvals, :grid266, :string
    add_column :approvals, :grid267, :string
    add_column :approvals, :grid271, :string
    add_column :approvals, :grid272, :string
    add_column :approvals, :grid273, :string
    add_column :approvals, :grid274, :string
    add_column :approvals, :grid275, :string
    add_column :approvals, :grid276, :string
    add_column :approvals, :grid277, :string
    add_column :approvals, :grid281, :string
    add_column :approvals, :grid282, :string
    add_column :approvals, :grid283, :string
    add_column :approvals, :grid284, :string
    add_column :approvals, :grid285, :string
    add_column :approvals, :grid286, :string
    add_column :approvals, :grid287, :string
    add_column :approvals, :grid291, :string
    add_column :approvals, :grid292, :string
    add_column :approvals, :grid293, :string
    add_column :approvals, :grid294, :string
    add_column :approvals, :grid295, :string
    add_column :approvals, :grid296, :string
    add_column :approvals, :grid297, :string
    add_column :approvals, :grid301, :string
    add_column :approvals, :grid302, :string
    add_column :approvals, :grid303, :string
    add_column :approvals, :grid304, :string
    add_column :approvals, :grid305, :string
    add_column :approvals, :grid306, :string
    add_column :approvals, :grid307, :string
  end
end
