class AddGrid2ToRota < ActiveRecord::Migration
  def change
    add_column :rota, :grid121, :string
    add_column :rota, :grid122, :string
    add_column :rota, :grid123, :string
    add_column :rota, :grid124, :string
    add_column :rota, :grid125, :string
    add_column :rota, :grid126, :string
    add_column :rota, :grid127, :string
    add_column :rota, :grid131, :string
    add_column :rota, :grid132, :string
    add_column :rota, :grid133, :string
    add_column :rota, :grid134, :string
    add_column :rota, :grid135, :string
    add_column :rota, :grid136, :string
    add_column :rota, :grid137, :string
    add_column :rota, :grid141, :string
    add_column :rota, :grid142, :string
    add_column :rota, :grid143, :string
    add_column :rota, :grid144, :string
    add_column :rota, :grid145, :string
    add_column :rota, :grid146, :string
    add_column :rota, :grid147, :string
    add_column :rota, :grid151, :string
    add_column :rota, :grid152, :string
    add_column :rota, :grid153, :string
    add_column :rota, :grid154, :string
    add_column :rota, :grid155, :string
    add_column :rota, :grid156, :string
    add_column :rota, :grid157, :string
    add_column :rota, :grid161, :string
    add_column :rota, :grid162, :string
    add_column :rota, :grid163, :string
    add_column :rota, :grid164, :string
    add_column :rota, :grid165, :string
    add_column :rota, :grid166, :string
    add_column :rota, :grid167, :string
    add_column :rota, :grid171, :string
    add_column :rota, :grid172, :string
    add_column :rota, :grid173, :string
    add_column :rota, :grid174, :string
    add_column :rota, :grid175, :string
    add_column :rota, :grid176, :string
    add_column :rota, :grid177, :string
    add_column :rota, :grid181, :string
    add_column :rota, :grid182, :string
    add_column :rota, :grid183, :string
    add_column :rota, :grid184, :string
    add_column :rota, :grid185, :string
    add_column :rota, :grid186, :string
    add_column :rota, :grid187, :string
    add_column :rota, :grid191, :string
    add_column :rota, :grid192, :string
    add_column :rota, :grid193, :string
    add_column :rota, :grid194, :string
    add_column :rota, :grid195, :string
    add_column :rota, :grid196, :string
    add_column :rota, :grid197, :string
    add_column :rota, :grid201, :string
    add_column :rota, :grid202, :string
    add_column :rota, :grid203, :string
    add_column :rota, :grid204, :string
    add_column :rota, :grid205, :string
    add_column :rota, :grid206, :string
    add_column :rota, :grid207, :string
    add_column :rota, :grid211, :string
    add_column :rota, :grid212, :string
    add_column :rota, :grid213, :string
    add_column :rota, :grid214, :string
    add_column :rota, :grid215, :string
    add_column :rota, :grid216, :string
    add_column :rota, :grid217, :string
    add_column :rota, :grid221, :string
    add_column :rota, :grid222, :string
    add_column :rota, :grid223, :string
    add_column :rota, :grid224, :string
    add_column :rota, :grid225, :string
    add_column :rota, :grid226, :string
    add_column :rota, :grid227, :string
    add_column :rota, :grid231, :string
    add_column :rota, :grid232, :string
    add_column :rota, :grid233, :string
    add_column :rota, :grid234, :string
    add_column :rota, :grid235, :string
    add_column :rota, :grid236, :string
    add_column :rota, :grid237, :string
    add_column :rota, :grid241, :string
    add_column :rota, :grid242, :string
    add_column :rota, :grid243, :string
    add_column :rota, :grid244, :string
    add_column :rota, :grid245, :string
    add_column :rota, :grid246, :string
    add_column :rota, :grid247, :string
    add_column :rota, :grid251, :string
    add_column :rota, :grid252, :string
    add_column :rota, :grid253, :string
    add_column :rota, :grid254, :string
    add_column :rota, :grid255, :string
    add_column :rota, :grid256, :string
    add_column :rota, :grid257, :string
    add_column :rota, :grid261, :string
    add_column :rota, :grid262, :string
    add_column :rota, :grid263, :string
    add_column :rota, :grid264, :string
    add_column :rota, :grid265, :string
    add_column :rota, :grid266, :string
    add_column :rota, :grid267, :string
    add_column :rota, :grid271, :string
    add_column :rota, :grid272, :string
    add_column :rota, :grid273, :string
    add_column :rota, :grid274, :string
    add_column :rota, :grid275, :string
    add_column :rota, :grid276, :string
    add_column :rota, :grid277, :string
    add_column :rota, :grid281, :string
    add_column :rota, :grid282, :string
    add_column :rota, :grid283, :string
    add_column :rota, :grid284, :string
    add_column :rota, :grid285, :string
    add_column :rota, :grid286, :string
    add_column :rota, :grid287, :string
    add_column :rota, :grid291, :string
    add_column :rota, :grid292, :string
    add_column :rota, :grid293, :string
    add_column :rota, :grid294, :string
    add_column :rota, :grid295, :string
    add_column :rota, :grid296, :string
    add_column :rota, :grid297, :string
    add_column :rota, :grid301, :string
    add_column :rota, :grid302, :string
    add_column :rota, :grid303, :string
    add_column :rota, :grid304, :string
    add_column :rota, :grid305, :string
    add_column :rota, :grid306, :string
    add_column :rota, :grid307, :string
  end
end
