class AddGridToRota < ActiveRecord::Migration
  def change
    add_column :rota, :grid11, :string
    add_column :rota, :grid12, :string
    add_column :rota, :grid13, :string
    add_column :rota, :grid14, :string
    add_column :rota, :grid15, :string
    add_column :rota, :grid16, :string
    add_column :rota, :grid17, :string
    add_column :rota, :grid21, :string
    add_column :rota, :grid22, :string
    add_column :rota, :grid23, :string
    add_column :rota, :grid24, :string
    add_column :rota, :grid25, :string
    add_column :rota, :grid26, :string
    add_column :rota, :grid27, :string
    add_column :rota, :grid31, :string
    add_column :rota, :grid32, :string
    add_column :rota, :grid33, :string
    add_column :rota, :grid34, :string
    add_column :rota, :grid35, :string
    add_column :rota, :grid36, :string
    add_column :rota, :grid37, :string
    add_column :rota, :grid41, :string
    add_column :rota, :grid42, :string
    add_column :rota, :grid43, :string
    add_column :rota, :grid44, :string
    add_column :rota, :grid45, :string
    add_column :rota, :grid46, :string
    add_column :rota, :grid47, :string
    add_column :rota, :grid51, :string
    add_column :rota, :grid52, :string
    add_column :rota, :grid53, :string
    add_column :rota, :grid54, :string
    add_column :rota, :grid55, :string
    add_column :rota, :grid56, :string
    add_column :rota, :grid57, :string
    add_column :rota, :grid61, :string
    add_column :rota, :grid62, :string
    add_column :rota, :grid63, :string
    add_column :rota, :grid64, :string
    add_column :rota, :grid65, :string
    add_column :rota, :grid66, :string
    add_column :rota, :grid67, :string
    add_column :rota, :grid71, :string
    add_column :rota, :grid72, :string
    add_column :rota, :grid73, :string
    add_column :rota, :grid74, :string
    add_column :rota, :grid75, :string
    add_column :rota, :grid76, :string
    add_column :rota, :grid77, :string
    add_column :rota, :grid81, :string
    add_column :rota, :grid82, :string
    add_column :rota, :grid83, :string
    add_column :rota, :grid84, :string
    add_column :rota, :grid85, :string
    add_column :rota, :grid86, :string
    add_column :rota, :grid87, :string
    add_column :rota, :grid91, :string
    add_column :rota, :grid92, :string
    add_column :rota, :grid93, :string
    add_column :rota, :grid94, :string
    add_column :rota, :grid95, :string
    add_column :rota, :grid96, :string
    add_column :rota, :grid97, :string
    add_column :rota, :grid101, :string
    add_column :rota, :grid102, :string
    add_column :rota, :grid103, :string
    add_column :rota, :grid104, :string
    add_column :rota, :grid105, :string
    add_column :rota, :grid106, :string
    add_column :rota, :grid107, :string
    add_column :rota, :grid111, :string
    add_column :rota, :grid112, :string
    add_column :rota, :grid113, :string
    add_column :rota, :grid114, :string
    add_column :rota, :grid115, :string
    add_column :rota, :grid116, :string
    add_column :rota, :grid117, :string
  end
end
