class AddGridToApproval < ActiveRecord::Migration
  def change
    add_column :approvals, :grid11, :string
    add_column :approvals, :grid12, :string
    add_column :approvals, :grid13, :string
    add_column :approvals, :grid14, :string
    add_column :approvals, :grid15, :string
    add_column :approvals, :grid16, :string
    add_column :approvals, :grid17, :string
    add_column :approvals, :grid21, :string
    add_column :approvals, :grid22, :string
    add_column :approvals, :grid23, :string
    add_column :approvals, :grid24, :string
    add_column :approvals, :grid25, :string
    add_column :approvals, :grid26, :string
    add_column :approvals, :grid27, :string
    add_column :approvals, :grid31, :string
    add_column :approvals, :grid32, :string
    add_column :approvals, :grid33, :string
    add_column :approvals, :grid34, :string
    add_column :approvals, :grid35, :string
    add_column :approvals, :grid36, :string
    add_column :approvals, :grid37, :string
    add_column :approvals, :grid41, :string
    add_column :approvals, :grid42, :string
    add_column :approvals, :grid43, :string
    add_column :approvals, :grid44, :string
    add_column :approvals, :grid45, :string
    add_column :approvals, :grid46, :string
    add_column :approvals, :grid47, :string
    add_column :approvals, :grid51, :string
    add_column :approvals, :grid52, :string
    add_column :approvals, :grid53, :string
    add_column :approvals, :grid54, :string
    add_column :approvals, :grid55, :string
    add_column :approvals, :grid56, :string
    add_column :approvals, :grid57, :string
    add_column :approvals, :grid61, :string
    add_column :approvals, :grid62, :string
    add_column :approvals, :grid63, :string
    add_column :approvals, :grid64, :string
    add_column :approvals, :grid65, :string
    add_column :approvals, :grid66, :string
    add_column :approvals, :grid67, :string
    add_column :approvals, :grid71, :string
    add_column :approvals, :grid72, :string
    add_column :approvals, :grid73, :string
    add_column :approvals, :grid74, :string
    add_column :approvals, :grid75, :string
    add_column :approvals, :grid76, :string
    add_column :approvals, :grid77, :string
    add_column :approvals, :grid81, :string
    add_column :approvals, :grid82, :string
    add_column :approvals, :grid83, :string
    add_column :approvals, :grid84, :string
    add_column :approvals, :grid85, :string
    add_column :approvals, :grid86, :string
    add_column :approvals, :grid87, :string
    add_column :approvals, :grid91, :string
    add_column :approvals, :grid92, :string
    add_column :approvals, :grid93, :string
    add_column :approvals, :grid94, :string
    add_column :approvals, :grid95, :string
    add_column :approvals, :grid96, :string
    add_column :approvals, :grid97, :string
    add_column :approvals, :grid101, :string
    add_column :approvals, :grid102, :string
    add_column :approvals, :grid103, :string
    add_column :approvals, :grid104, :string
    add_column :approvals, :grid105, :string
    add_column :approvals, :grid106, :string
    add_column :approvals, :grid107, :string
    add_column :approvals, :grid111, :string
    add_column :approvals, :grid112, :string
    add_column :approvals, :grid113, :string
    add_column :approvals, :grid114, :string
    add_column :approvals, :grid115, :string
    add_column :approvals, :grid116, :string
    add_column :approvals, :grid117, :string
  end
end
